# Generated by Django 5.1.2 on 2024-11-14 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('UserID', models.AutoField(primary_key=True, serialize=False)),
                ('Username', models.CharField(max_length=150, unique=True)),
                ('Password', models.CharField(max_length=128)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Role', models.CharField(max_length=50)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('UpdatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
