# Generated by Django 5.1.2 on 2024-11-14 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_user_usersandadmins_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('ReportID', models.AutoField(primary_key=True, serialize=False)),
                ('CrimeType', models.CharField(max_length=100)),
                ('Description', models.TextField()),
                ('Location', models.CharField(max_length=255)),
                ('Status', models.CharField(max_length=50)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('UpdatedAt', models.DateTimeField(auto_now=True)),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.usersandadmins')),
            ],
        ),
    ]
