# Generated by Django 5.1.2 on 2024-11-15 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='MostWanted',
            fields=[
                ('CriminalID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=150)),
                ('Description', models.TextField()),
                ('LastKnownLocation', models.CharField(max_length=255)),
                ('CrimeType', models.CharField(max_length=100)),
                ('Reward', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('UpdatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
