# Generated by Django 5.1.2 on 2024-11-15 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_mostwanted'),
    ]

    operations = [
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('ProgressID', models.AutoField(primary_key=True, serialize=False)),
                ('StatusUpdate', models.TextField()),
                ('UpdatedAt', models.DateTimeField(auto_now=True)),
                ('ReportID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.report')),
            ],
        ),
    ]
