# Generated by Django 5.1.2 on 2024-11-15 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_progress'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRoles',
            fields=[
                ('RoleID', models.AutoField(primary_key=True, serialize=False)),
                ('RoleName', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
