# Generated by Django 5.1.2 on 2024-11-15 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_notifications'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrimeCategories',
            fields=[
                ('CategoryID', models.AutoField(primary_key=True, serialize=False)),
                ('CategoryName', models.CharField(max_length=100, unique=True)),
                ('Description', models.TextField()),
            ],
        ),
    ]
