# Generated by Django 5.1.2 on 2024-11-15 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminLogs',
            fields=[
                ('LogID', models.AutoField(primary_key=True, serialize=False)),
                ('Action', models.CharField(max_length=255)),
                ('Timestamp', models.DateTimeField(auto_now_add=True)),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.usersandadmins')),
            ],
        ),
    ]
