# Generated by Django 5.1.2 on 2024-11-15 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_case'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachments',
            fields=[
                ('AttachmentID', models.AutoField(primary_key=True, serialize=False)),
                ('FilePath', models.FileField(upload_to='attachments/')),
                ('FileType', models.CharField(max_length=50)),
                ('UploadedAt', models.DateTimeField(auto_now_add=True)),
                ('ReportID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.report')),
            ],
        ),
    ]
