# Generated by Django 5.1.2 on 2024-11-16 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_resource'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='crime_reports/'),
        ),
        migrations.AlterField(
            model_name='report',
            name='Status',
            field=models.CharField(default='Open', max_length=50),
        ),
    ]
