# Generated by Django 5.1.2 on 2024-11-16 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_userinfo_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportedCrime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('location', models.CharField(max_length=255)),
                ('victims', models.TextField(blank=True)),
                ('crime_type', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='crime_images/')),
            ],
        ),
    ]
