# Generated by Django 5.1.2 on 2024-11-18 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_intelligenceofficer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IntelligenceOfficer',
        ),
    ]
