# Generated by Django 5.1.2 on 2024-11-19 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_officer'),
    ]

    operations = [
        migrations.AddField(
            model_name='officer',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('resolved', 'Resolved'), ('suspended', 'Suspended')], default='active', max_length=10),
        ),
    ]
