# Generated by Django 5.1.2 on 2024-11-19 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_remove_officer_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='crimereport',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('resolved', 'Resolved'), ('in_progress', 'In Progress')], default='open', max_length=20),
        ),
    ]
