# Generated by Django 5.1.2 on 2024-11-20 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0029_alter_crimereport_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='crimereport',
            name='report_id',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
