# Generated by Django 5.1.2 on 2024-11-20 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0031_remove_crimereport_report_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='crimereport',
            name='report_id',
            field=models.CharField(editable=False, max_length=10, null=True, unique=True),
        ),
    ]
