# Generated by Django 5.1.2 on 2024-11-20 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0032_crimereport_report_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crimereport',
            name='report_id',
        ),
    ]
