# Generated by Django 5.1.2 on 2024-11-23 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0034_alter_crimereport_options_crimereport_report_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crimereport',
            name='report_id',
            field=models.CharField(editable=False, max_length=20, unique=True),
        ),
    ]
