# Generated by Django 5.1.2 on 2024-11-23 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0035_alter_crimereport_report_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crimereport',
            options={},
        ),
        migrations.RemoveField(
            model_name='crimereport',
            name='report_id',
        ),
    ]
