# Generated by Django 5.1.2 on 2024-12-10 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0041_remove_feedback_created_at_alter_feedback_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='mostwanted',
            name='status',
            field=models.CharField(choices=[('seen', 'Seen'), ('not_seen', 'Not Seen')], default='not_seen', max_length=10),
        ),
    ]
