# Generated by Django 5.1.2 on 2024-12-11 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0042_mostwanted_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
